version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./React
    ports:
      - "5173:5173"
    volumes:
      - ./React:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
